# You can add on to this file but you are not allowed to change the setup
# provided below or the location of this file. If you do, you will fail
# the auto-graded tests and likely receive a harsh penalty.

all: doublet 

doublet: doublet.cpp Minheap.h doublet
	g++ -Wall -Ilib -g doublet.cpp -o doublet
# ADD WHATEVER ELSE YOU NEED HERE
.PHONY: clean
clean:
	rm doublet